# Generated by Django 4.0.5 on 2022-07-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_wewnetrzny', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_przegladu_technicznego', models.DateField(blank=True, null=True)),
                ('data_przegladu_serwisowego', models.DateField(blank=True, null=True)),
                ('przebieg', models.PositiveIntegerField(default=0)),
                ('rodzaj_silnika', models.CharField(choices=[('PB', 'Benzyna'), ('ON', 'Diesel'), ('Ele', 'Elektryczny'), ('Hybr', 'Hybryda'), (' ', ' ')], default='', max_length=4)),
                ('opis', models.TextField(blank=True, default='')),
            ],
        ),
    ]
