# Generated by Django 4.0.5 on 2022-07-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='model',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='cars',
            name='rodzaj_silnika',
            field=models.CharField(choices=[('PB', 'Benzyna'), ('ON', 'Diesel'), ('Ele', 'Elektryczny'), ('Hybr', 'Hybrydowy'), ('', '')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='cars',
            name='rok_produkcji',
            field=models.PositiveSmallIntegerField(default=1970, max_length=4),
        ),
        migrations.AlterField(
            model_name='cars',
            name='marka',
            field=models.CharField(default='', max_length=32),
        ),
    ]
