# Generated by Django 4.0.5 on 2022-07-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_cars_data_przegladu_serwisowego_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='przebieg',
            field=models.PositiveIntegerField(default=0, max_length=7),
        ),
    ]
