# Generated by Django 4.0.5 on 2022-07-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_cars_nr_wewnetrzny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='opis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cars',
            name='rodzaj_silnika',
            field=models.CharField(choices=[('PB', 'Benzyna'), ('ON', 'Diesel'), ('Ele', 'Elektryczny'), ('Hybr', 'Hybrydowy'), (' ', ' ')], default='', max_length=4),
        ),
    ]
